[package]
name = "nmea"
version = "0.0.4-pre"
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
description = "Simple NMEA 0183 parser"
documentation = "https://docs.rs/nmea/"
homepage = "https://github.com/flxo/rust-nmea"
license = "Apache-2.0"
keywords = ["NMEA", "gps", "glonass", "coordinate", "position"]

[dependencies]
regex = "0.2.1"
lazy_static = "0.2.2"
chrono = "0.2.25"

[dev-dependencies]
quickcheck = "0.3"

